# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Unresolved'), (1, 'Rescue in Progress'), (2, 'Rescued'), (3, 'Adopted')], default=0)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescuteApp.Category')),
            ],
        ),
    ]
