# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 01:38
from __future__ import unicode_literals

from django.db import migrations

def addCategories(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("rescuteApp", "Category")
    category1 = Category(animal_type='Dog')
    category1.save()
    category2 = Category(animal_type='Cat')
    category2.save()
    



class Migration(migrations.Migration):

    dependencies = [
        ('rescuteApp', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(addCategories),
    ]
