# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuteApp', '0003_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='additional_comments',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
